# Meta Data for SEO

## Homepage
title = "Filecoin Docs"
titleSeparator = "-"
titleAddition = "Home"
description = "Documentation for Filecoin - A decentralized storage network for humanity's most important information."
useLogo = true

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["/logos/Filecoin-logo-blue+black.png"]
ogLocale = "en_US"
domainTLD = "docs.filecoin.io"
titleHome = "Filecoin Docs"

## Twitter Cards
twitterSite = "@filecoin"
twitterCreator = "@protocollabs"

## JSON-LD
schemaType = "Organization"
schemaName = "Filecoin"
schemaAuthor = "Protocol Labs"
schemaAuthorTwitter = "https://twitter.com/filecoin"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/filecoin/"
schemaAuthorGitHub = "https://github.com/filecoin-project"
schemaLocale = "en-US"
schemaLogo = "filecoin.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "filecoin.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/filecoin"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/filecoin-project/filecoin-docs"
schemaSection = "blog"


## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = ""
footer_link = ""

# Feed
copyRight = ""

# Alert
alert = true
alertDismissable = true
alertText = "You are viewing the <b>legacy version</b> of Filecoin Docs. This website is no longer maintained, and the content may be out of date. To view the current Filecoin Docs, head over to <a style='color: purple' href='https://docs.filecoin.io'>docs.filecoin.io</a>. DNS for this site will be removed on 2023-09-30. Copies will continue to be available over IPFS."

# Edit Page
repoHost = "GitHub"
docsRepo = "https://github.com/filecoin-project/filecoin-docs"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = true
lastMod = true

[sections]
  sectionNav = ["about", "intro", "store", "providers", "smart-contracts", "reference"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = false
  flexSearch = true
  searchSectionsShow = "ALL"
  searchSectionsIndex = ["about", "intro", "store", "providers", "smart-contracts", "reference"]
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1
  progressBar = true


[menu]
  [menu.section]
    auto = false
    collapsibleSidebar = false
